CREATE TABLE IF NOT EXISTS  public.favorite(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_id integer NOT NULL,
    inventory_id integer NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.favorite
    OWNER to cse340;